Vagrant.configure("2") do |config|
  config.vm.box = ENV.fetch("VAGRANT_BOX_NAME", "linux-ubuntu-server-packer")
  hyperv_switch = ENV.fetch("VAGRANT_HYPERV_SWITCH", "Default Switch")
  config.vm.network "public_network", bridge: hyperv_switch
  
  config.vm.provider "hyperv" do |h|
    h.vmname = ENV.fetch("VAGRANT_VM_NAME", "linux-ubuntu-packer")
    h.memory = 4096
    h.cpus = 2
    h.enable_virtualization_extensions = true
  end

  config.vm.communicator = "ssh"
  config.vm.guest = :linux
  config.vm.boot_timeout = 600

  # Optional: Set up SSH credentials if needed
  config.ssh.username = "packer"
  config.ssh.password = "P@ssw0rd!"

  # Disable all synced folders (including default /vagrant)
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
