version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/.devcontainer"
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: "/scripts/macos"
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: "/scripts/gh-runner-func"
    schedule:
      interval: weekly
