---
# macOS: install via Homebrew
- name: Install kubelogin on macOS (int128)
  homebrew:
    name: kubelogin
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

# Linux: download latest release from GitHub
- name: Get latest int128/kubelogin release info from GitHub
  uri:
    url: https://api.github.com/repos/int128/kubelogin/releases/latest
    return_content: yes
  register: kubelogin_release
  when: ansible_facts['os_family'] == 'Debian'

- name: Set kubelogin download URL for Linux
  set_fact:
    kubelogin_linux_url: >-
      {{
        kubelogin_release.json.assets
        | selectattr('name', 'match', 'kubelogin-linux-amd64.zip')
        | list | first.browser_download_url
      }}
  when: ansible_facts['os_family'] == 'Debian'

- name: Download kubelogin archive (Linux)
  get_url:
    url: "{{ kubelogin_linux_url }}"
    dest: "/tmp/kubelogin.zip"
    mode: '0644'
  when: ansible_facts['os_family'] == 'Debian'

- name: Ensure unzip is installed (Linux)
  apt:
    name: unzip
    state: present
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Unarchive kubelogin (Linux)
  unarchive:
    src: "/tmp/kubelogin.zip"
    dest: "/usr/local/bin/"
    remote_src: yes
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Set executable permissions for kubelogin (Linux)
  file:
    path: /usr/local/bin/kubelogin
    mode: '0755'
  become: true
  when: ansible_facts['os_family'] == 'Debian'

# Windows (assumes PowerShell and administrator rights)
- name: Set kubelogin download URL for Windows
  set_fact:
    kubelogin_windows_url: >-
      {{
        kubelogin_release.json.assets
        | selectattr('name', 'match', 'kubelogin-windows-amd64.zip')
        | list | first.browser_download_url
      }}
  when: ansible_facts['os_family'] == 'Windows'

- name: Download kubelogin archive (Windows)
  win_get_url:
    url: "{{ kubelogin_windows_url }}"
    dest: C:\Temp\kubelogin.zip
  when: ansible_facts['os_family'] == 'Windows'

- name: Ensure destination directory exists (Windows)
  win_file:
    path: C:\Tools\kubelogin
    state: directory
  when: ansible_facts['os_family'] == 'Windows'

- name: Unzip kubelogin binary (Windows)
  win_unzip:
    src: C:\Temp\kubelogin.zip
    dest: C:\Tools\kubelogin
    creates: C:\Tools\kubelogin\kubelogin.exe
  when: ansible_facts['os_family'] == 'Windows'

- name: Add kubelogin to system PATH (Windows)
  win_environment:
    name: Path
    value: C:\Tools\kubelogin
    state: present
    level: machine
  when: ansible_facts['os_family'] == 'Windows'
