- name: set the default shell to PowerShell
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\OpenSSH
    name: DefaultShell
    data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    type: string
    state: present
  when: ansible_connection == 'ssh'

- name: reset SSH connection after shell change
  ansible.builtin.meta: reset_connection
  when: ansible_connection == 'ssh'
