services:
  ansible-windows-test:
    build:
      context: ../../../build/docker/ansible-windows/
    container_name: ansible-windows-test
    volumes:
      - ../../../:C:\src
    entrypoint: []
    command: C:\\cygwin64\\bin\\bash.exe -l -c "cd /cygdrive/c/src/ && ansible-playbook playbooks/setup.yml -i inventory/localhost_windows.yml -l windows_host" # --tags='java'
    tty: true
    dns:
      - 8.8.8.8
      - 1.1.1.1
