Vagrant.configure("2") do |config|
  config.vm.box = "win11-packer"
  
  config.vm.provider "hyperv" do |h|
    h.vmname = "win11-packer"
    h.memory = 4096
    h.cpus = 2
    h.enable_virtualization_extensions = true
  end

  config.vm.communicator = "winrm"
  config.vm.guest = :windows
  config.vm.boot_timeout = 600

  # Optional: Set up WinRM credentials if needed
  config.winrm.username = "Administrator"
  config.winrm.password = "P@ssw0rd!"

  # Disable all synced folders (including default /vagrant)
  config.vm.synced_folder ".", "/vagrant", disabled: true
end