- name: Get current user
  ansible.builtin.command: whoami
  register: current_user

- set_fact:
    ansible_user: "{{ current_user.stdout }}"
  when: ansible_user is not defined

- name: Ensure passwordless sudo for {{ ansible_user }} user
  become: true
  copy:
    dest: /etc/sudoers.d/{{ ansible_user }}
    content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: wheel
    mode: "0440"

- name: Check if Rosetta 2 is installed
  stat:
    path: /usr/libexec/rosetta
  register: rosetta_stat

- set_fact:
    rosetta_installed: "{{ rosetta_stat.stat.exists }}"

- name: Install Rosetta 2 if JDK 8 is required and Rosetta is not installed
  become: true
  command: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
  when:
    - 8 in jdk_versions
    - rosetta_installed is not defined or not rosetta_installed

- name: Install Homebrew Temurin casks
  community.general.homebrew_cask:
    name: "{{ 'temurin' if item == 24 else 'temurin@' ~ item }}"
    state: present
  loop: "{{ jdk_versions }}"

- name: Install jenv with Homebrew
  community.general.homebrew:
    name: jenv
    state: present

- name: Check if .zshrc exists
  stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: zshrc_stat

- name: Add jenv init to shell config
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'eval "$(jenv init -)"'
    insertafter: EOF
    create: yes

- name: Add Java versions to jenv
  shell: |
    export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
    jenv add "$JAVA_HOME"
  environment:
    JAVA_HOME: "{{ lookup('pipe', '/usr/libexec/java_home -v ' ~ item) }}"
  loop: "{{ jdk_versions }}"

- name: Create .zshrc if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/.zshrc"
    state: touch
    mode: "0644"
  when: not zshrc_stat.stat.exists

- name: Set global Java version via jenv
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "jenv global {{ jdk_default_version }}"
    insertafter: EOF

- name: Ensure jenv plugins directory exists
  file:
    path: "{{ ansible_env.HOME }}/.jenv/plugins"
    state: directory
    mode: "0755"

- name: Enable jenv plugin maven
  shell: |
    export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
    eval "$(jenv init -)"
    jenv enable-plugin maven
  args:
    executable: /bin/zsh

- name: Remove passwordless sudo for {{ ansible_user }} user
  become: true
  file:
    path: /etc/sudoers.d/{{ ansible_user }}
    state: absent
