name: Build and Push Windows Ansible Container

on:
  push:
    branches: [main, feat*]
    paths:
      - "build/docker/ansible-windows-ssh/Dockerfile"
      - "build/docker/ansible-windows-winrm/Dockerfile"
      - ".github/workflows/build-ansible-windows-ssh.yml"
      - ".github/workflows/build-ansible-windows-winrm.yml"
  pull_request:
    branches: [main, feat*]
    paths:
      - "build/docker/ansible-windows-ssh/Dockerfile"
      - "build/docker/ansible-windows-winrm/Dockerfile"
      - ".github/workflows/build-ansible-windows-ssh.yml"
      - ".github/workflows/build-ansible-windows-winrm.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: windows-2025
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        ansible_protocol: [ssh, winrm]
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/dev-alchemy-ansible
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        shell: powershell
        run: |
          cd build/docker/ansible-windows-${{ matrix.ansible_protocol }}
          docker build . -t ${{ env.IMAGE_NAME }}:windows-${{ matrix.ansible_protocol }}

      - name: push container
        shell: powershell
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: |
          docker push ${{ env.IMAGE_NAME }}:windows-${{ matrix.ansible_protocol }}
