name: Build and Push Container Image for Ansible on Ubuntu

on:
  push:
    branches: [main, feat*]
    paths:
      - "build/docker/ansible/Dockerfile"
      - ".github/workflows/build-ansible-ubuntu.yml"
  pull_request:
    branches: [main, feat*]
    paths:
      - "build/docker/ansible/Dockerfile"
      - ".github/workflows/build-ansible-ubuntu.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/docker/ansible/Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/dev-alchemy-ansible:ubuntu

      - name: push container
        shell: powershell
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/dev-alchemy-ansible:ubuntu
