# GitHub Actions workflow to test all Ansible roles on Windows, macOS, and Ubuntu
name: Test Ansible Roles

on:
  push:
    branches: [main, feat*]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main, feat*]
    paths-ignore:
      - "**/*.md"

jobs:
  test-ansible-roles:
    name: Test Ansible Roles on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Uncomment the following line to test on all specified OSs
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Display Ansible version
        run: ansible --version

      - name: Run all Ansible roles
        shell: bash
        run: |
          for role in roles/*; do
            if [ -d "$role/tasks" ]; then
              echo "Testing role: $role"
              ansible-playbook -i inventory/localhost.yaml playbooks/setup.yml --tags "$(basename $role)" || exit 1
            fi
          done
        env:
          ANSIBLE_FORCE_COLOR: "true"
