name: Test Go Unit Tests

on:
  push:
    paths:
      - "cmd/cmd/**"
      - ".github/workflows/test-cmd-unit-tests.yml"
      - "pkg/build/**"
      - "pkg/deploy/**"
  pull_request:
    paths:
      - "cmd/cmd/**"
      - ".github/workflows/test-cmd-unit-tests.yml"
      - "pkg/build/**"
      - "pkg/deploy/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Run cmd unit tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run cmd tests
        run: go test ./cmd/cmd/...

      - name: Run deploy package tests
        run: go test ./pkg/deploy/...

      - name: Run build package tests
        run: go test ./pkg/build/...
